[tools]
go = "1.26.3"
golangci-lint = "2.12.2"

[tasks.install]
description = "Build and install the plugin to ~/.tflint.d/plugins"
run = """
go build
mkdir -p ~/.tflint.d/plugins
mv ./tflint-ruleset-sort ~/.tflint.d/plugins/tflint-ruleset-sort
"""

[settings]
lockfile = true
